name: shifushotlocal
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^3.10.1
  firebase_auth: ^5.4.1
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: jaro
      fonts:
        - asset: assets/fonts/Jaro-Regular-VariableFont_opsz.ttf
    - family: afacad
      fonts:
        - asset: assets/fonts/Afacad-Regular.otf
        - asset: assets/fonts/Afacad-Bold.otf
        - asset: assets/fonts/Afacad-Italic.otf
        - asset: assets/fonts/Afacad-Medium.otf
        - asset: assets/fonts/Afacad-SemiBold.otf
  assets:
    - assets/images/logo.png
    - assets/images/cheers.png
    - assets/images/favicon.png
