name: shifushotlocal
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  audioplayers: ^6.4.0
  cloud_firestore: ^5.6.2
  cloud_functions: ^5.3.4
  confetti: ^0.8.0
  dice_icons: ^0.1.7
  firebase_admin: ^0.3.0+1
  firebase_auth: ^5.4.1
  firebase_core: ^3.10.1
  firebase_messaging: ^15.2.4
  firebase_storage: ^12.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^19.2.0
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  playing_cards: ^0.4.1+11
  playing_cards_layouts: ^1.0.1
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  vibration: ^3.1.3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: jaro
      fonts:
        - asset: assets/fonts/Jaro-Regular-VariableFont_opsz.ttf
    - family: afacad
      fonts:
        - asset: assets/fonts/Afacad-Regular.otf
        - asset: assets/fonts/Afacad-Bold.otf
        - asset: assets/fonts/Afacad-Italic.otf
        - asset: assets/fonts/Afacad-Medium.otf
        - asset: assets/fonts/Afacad-SemiBold.otf
  assets:
    - assets/images/logo.png
    - assets/images/cheers.png
    - assets/images/favicon.png
    - assets/jsons/killer_actions.json
    - assets/jsons/papers.json
    - assets/jsons/debate.json
    - assets/images/papier_dechire.png
    - assets/images/feedback_icon.png
    - assets/images/tapis_de_jeu.png
    - assets/images/app_icon.png
    - assets/images/logo_icon.png
    - assets/images/icon2.png
    - assets/audios/pet/pet1.mp3
    - assets/audios/pet/pet2.mp3
    - assets/audios/pet/pet3.mp3
    - assets/audios/pet/pet4.mp3
    - assets/audios/pet/petponey1.mp3
    - assets/audios/pet_crosnier/PetCrosnier1.mp3
    - assets/audios/pet_crosnier/PetCrosnier2.mp3
    - assets/audios/pet_crosnier/PetCrosnier3.mp3
    - assets/audios/pet_crosnier/PetCrosnier4.mp3
    - assets/audios/pet_crosnier/PetCrosnier5.mp3
    - assets/audios/pet_crosnier/PetCrosnier6.mp3
    - assets/audios/pet_crosnier/PetCrosnier7.mp3
    - assets/audios/pet_crosnier/PetCrosnier8.mp3
    - assets/audios/pet_crosnier/PetCrosnier9.mp3
    - assets/audios/pet_crosnier/PetCrosnier10.mp3
    - assets/audios/pet_crosnier/PetCrosnier11.mp3
    - assets/audios/pet_crosnier/PetCrosnier12.mp3
    - assets/audios/pet_crosnier/PetCrosnier13.mp3
    - assets/audios/pet_crosnier/PetCrosnier14.mp3
    - assets/audios/pet_crosnier/PetCrosnier15.mp3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon2.png"
  adaptive_icon_background: "#FAEADC" # Fond pour Android 8.0+
  adaptive_icon_foreground: "assets/images/icon2.png"
